
// Code generated by MetaFFI. DO NOT EDIT.
// Host code for py_extractor.json
package py_extractor

import "fmt"
import "unsafe"
import . "github.com/MetaFFI/lang-plugin-go/go-runtime"



// function IDs








var variable_info_get_name_id unsafe.Pointer


var variable_info_get_type_id unsafe.Pointer


var variable_info_get_is_getter_id unsafe.Pointer


var variable_info_get_is_setter_id unsafe.Pointer





var variable_info_Releasevariable_info_id unsafe.Pointer



var parameter_info_get_name_id unsafe.Pointer


var parameter_info_get_type_id unsafe.Pointer


var parameter_info_get_is_default_value_id unsafe.Pointer


var parameter_info_get_is_optional_id unsafe.Pointer


var parameter_info_get_kind_id unsafe.Pointer





var parameter_info_Releaseparameter_info_id unsafe.Pointer



var function_info_get_name_id unsafe.Pointer


var function_info_get_comment_id unsafe.Pointer


var function_info_get_parameters_id unsafe.Pointer


var function_info_get_return_values_id unsafe.Pointer





var function_info_Releasefunction_info_id unsafe.Pointer



var class_info_get_name_id unsafe.Pointer


var class_info_get_comment_id unsafe.Pointer


var class_info_get_fields_id unsafe.Pointer


var class_info_get_methods_id unsafe.Pointer





var class_info_Releaseclass_info_id unsafe.Pointer



var py_info_get_globals_id unsafe.Pointer


var py_info_get_functions_id unsafe.Pointer


var py_info_get_classes_id unsafe.Pointer





var py_info_Releasepy_info_id unsafe.Pointer




var py_extractor_extract_id unsafe.Pointer


var py_extractor_py_extractor_id unsafe.Pointer


var py_extractor_Releasepy_extractor_id unsafe.Pointer




func Load(modulePath string){
	LoadCDTCAPI()

	runtimePlugin := "xllr.python3"
	err := XLLRLoadRuntimePlugin(runtimePlugin)
	if err != nil{
		panic(err)
	}

	// load functions
	loadFF := func(modulePath string, fpath string, paramsCount int8, retvalCount int8) unsafe.Pointer{
		id, err := XLLRLoadFunction(runtimePlugin, modulePath, fpath, nil, paramsCount, retvalCount)
		if err != nil{ // failed
			panic(err)
		}

		return id
	}

	
	

	

	
	
	variable_info_get_name_id = loadFF(modulePath, `entrypoint_function=EntryPoint_variable_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	variable_info_get_type_id = loadFF(modulePath, `entrypoint_function=EntryPoint_variable_info_get_type,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	variable_info_get_is_getter_id = loadFF(modulePath, `entrypoint_function=EntryPoint_variable_info_get_is_getter,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	variable_info_get_is_setter_id = loadFF(modulePath, `entrypoint_function=EntryPoint_variable_info_get_is_setter,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	
	
	
	variable_info_Releasevariable_info_id = loadFF(modulePath, `entrypoint_function=EntryPoint_variable_info_Releasevariable_info,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 0)
	
	
	
	parameter_info_get_name_id = loadFF(modulePath, `entrypoint_function=EntryPoint_parameter_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	parameter_info_get_type_id = loadFF(modulePath, `entrypoint_function=EntryPoint_parameter_info_get_type,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	parameter_info_get_is_default_value_id = loadFF(modulePath, `entrypoint_function=EntryPoint_parameter_info_get_is_default_value,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	parameter_info_get_is_optional_id = loadFF(modulePath, `entrypoint_function=EntryPoint_parameter_info_get_is_optional,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	parameter_info_get_kind_id = loadFF(modulePath, `entrypoint_function=EntryPoint_parameter_info_get_kind,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	
	
	
	parameter_info_Releaseparameter_info_id = loadFF(modulePath, `entrypoint_function=EntryPoint_parameter_info_Releaseparameter_info,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 0)
	
	
	
	function_info_get_name_id = loadFF(modulePath, `entrypoint_function=EntryPoint_function_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	function_info_get_comment_id = loadFF(modulePath, `entrypoint_function=EntryPoint_function_info_get_comment,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	function_info_get_parameters_id = loadFF(modulePath, `entrypoint_function=EntryPoint_function_info_get_parameters,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	function_info_get_return_values_id = loadFF(modulePath, `entrypoint_function=EntryPoint_function_info_get_return_values,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	
	
	
	function_info_Releasefunction_info_id = loadFF(modulePath, `entrypoint_function=EntryPoint_function_info_Releasefunction_info,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 0)
	
	
	
	class_info_get_name_id = loadFF(modulePath, `entrypoint_function=EntryPoint_class_info_get_name,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	class_info_get_comment_id = loadFF(modulePath, `entrypoint_function=EntryPoint_class_info_get_comment,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	class_info_get_fields_id = loadFF(modulePath, `entrypoint_function=EntryPoint_class_info_get_fields,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	class_info_get_methods_id = loadFF(modulePath, `entrypoint_function=EntryPoint_class_info_get_methods,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	
	
	
	class_info_Releaseclass_info_id = loadFF(modulePath, `entrypoint_function=EntryPoint_class_info_Releaseclass_info,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 0)
	
	
	
	py_info_get_globals_id = loadFF(modulePath, `entrypoint_function=EntryPoint_py_info_get_globals,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	py_info_get_functions_id = loadFF(modulePath, `entrypoint_function=EntryPoint_py_info_get_functions,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	py_info_get_classes_id = loadFF(modulePath, `entrypoint_function=EntryPoint_py_info_get_classes,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	
	
	
	py_info_Releasepy_info_id = loadFF(modulePath, `entrypoint_function=EntryPoint_py_info_Releasepy_info,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 0)
	
	
	
	
	py_extractor_extract_id = loadFF(modulePath, `entrypoint_class=py_extractor,entrypoint_function=EntryPoint_py_extractor_extract,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	py_extractor_py_extractor_id = loadFF(modulePath, `entrypoint_function=EntryPoint_py_extractor_py_extractor,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 1)
	
	
	py_extractor_Releasepy_extractor_id = loadFF(modulePath, `entrypoint_function=EntryPoint_py_extractor_Releasepy_extractor,metaffi_guest_lib=py_extractor_MetaFFIGuest,module=py_extractor`, 1, 0)
	
	
	
}

func Free(){
	err := XLLRFreeRuntimePlugin("xllr.python3")
	if err != nil{ panic(err) }
}









// Code to call foreign functions in module py_extractor via XLLR



type VariableInfo struct{
	h Handle
}



func (this *VariableInfo) GetHandle() Handle{
	return this.h
}

func (this *VariableInfo) SetHandle(h Handle){
	this.h = h
}



func (this *VariableInfo) GetName() (name string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(variable_info_get_name_id, xcall_params)  // call function pointer variable_info_get_name_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionvariable_info.get_name. Error: %v", err)
		return
	}

	
	
	nameAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if nameAsInterface != nil{
		
		// not handle
		name = string(nameAsInterface.(string))
		
		
	}

	

	return name, nil	
}




func (this *VariableInfo) GetType() (type__ string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(variable_info_get_type_id, xcall_params)  // call function pointer variable_info_get_type_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionvariable_info.get_type. Error: %v", err)
		return
	}

	
	
	type__AsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if type__AsInterface != nil{
		
		// not handle
		type__ = string(type__AsInterface.(string))
		
		
	}

	

	return type__, nil	
}




func (this *VariableInfo) GetIsGetter() (is_getter bool, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(variable_info_get_is_getter_id, xcall_params)  // call function pointer variable_info_get_is_getter_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionvariable_info.get_is_getter. Error: %v", err)
		return
	}

	
	
	is_getterAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if is_getterAsInterface != nil{
		
		// not handle
		is_getter = bool(is_getterAsInterface.(bool))
		
		
	}

	

	return is_getter, nil	
}




func (this *VariableInfo) GetIsSetter() (is_setter bool, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(variable_info_get_is_setter_id, xcall_params)  // call function pointer variable_info_get_is_setter_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionvariable_info.get_is_setter. Error: %v", err)
		return
	}

	
	
	is_setterAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if is_setterAsInterface != nil{
		
		// not handle
		is_setter = bool(is_setterAsInterface.(bool))
		
		
	}

	

	return is_setter, nil	
}





func (this *VariableInfo) ReleasevariableInfo( this_instance interface{}) ( err error){
	
	xcall_params, parametersCDTS, _ := XLLRAllocCDTSBuffer(1, 0)

	
	// parameters
	FromGoToCDT(this.h, parametersCDTS, 0) // object
	

		err = XLLRXCallParamsNoRet(variable_info_Releasevariable_info_id, xcall_params)  // call function pointer variable_info_Releasevariable_info_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionvariable_info.Releasevariable_info. Error: %v", err)
		return
	}

	
	

	return  nil
}


type ParameterInfo struct{
	h Handle
}



func (this *ParameterInfo) GetHandle() Handle{
	return this.h
}

func (this *ParameterInfo) SetHandle(h Handle){
	this.h = h
}



func (this *ParameterInfo) GetName() (name string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(parameter_info_get_name_id, xcall_params)  // call function pointer parameter_info_get_name_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionparameter_info.get_name. Error: %v", err)
		return
	}

	
	
	nameAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if nameAsInterface != nil{
		
		// not handle
		name = string(nameAsInterface.(string))
		
		
	}

	

	return name, nil	
}




func (this *ParameterInfo) GetType() (type__ string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(parameter_info_get_type_id, xcall_params)  // call function pointer parameter_info_get_type_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionparameter_info.get_type. Error: %v", err)
		return
	}

	
	
	type__AsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if type__AsInterface != nil{
		
		// not handle
		type__ = string(type__AsInterface.(string))
		
		
	}

	

	return type__, nil	
}




func (this *ParameterInfo) GetIsDefaultValue() (is_default_value bool, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(parameter_info_get_is_default_value_id, xcall_params)  // call function pointer parameter_info_get_is_default_value_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionparameter_info.get_is_default_value. Error: %v", err)
		return
	}

	
	
	is_default_valueAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if is_default_valueAsInterface != nil{
		
		// not handle
		is_default_value = bool(is_default_valueAsInterface.(bool))
		
		
	}

	

	return is_default_value, nil	
}




func (this *ParameterInfo) GetIsOptional() (is_optional bool, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(parameter_info_get_is_optional_id, xcall_params)  // call function pointer parameter_info_get_is_optional_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionparameter_info.get_is_optional. Error: %v", err)
		return
	}

	
	
	is_optionalAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if is_optionalAsInterface != nil{
		
		// not handle
		is_optional = bool(is_optionalAsInterface.(bool))
		
		
	}

	

	return is_optional, nil	
}




func (this *ParameterInfo) GetKind() (kind string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(parameter_info_get_kind_id, xcall_params)  // call function pointer parameter_info_get_kind_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionparameter_info.get_kind. Error: %v", err)
		return
	}

	
	
	kindAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if kindAsInterface != nil{
		
		// not handle
		kind = string(kindAsInterface.(string))
		
		
	}

	

	return kind, nil	
}





func (this *ParameterInfo) ReleaseparameterInfo( this_instance interface{}) ( err error){
	
	xcall_params, parametersCDTS, _ := XLLRAllocCDTSBuffer(1, 0)

	
	// parameters
	FromGoToCDT(this.h, parametersCDTS, 0) // object
	

		err = XLLRXCallParamsNoRet(parameter_info_Releaseparameter_info_id, xcall_params)  // call function pointer parameter_info_Releaseparameter_info_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionparameter_info.Releaseparameter_info. Error: %v", err)
		return
	}

	
	

	return  nil
}


type FunctionInfo struct{
	h Handle
}



func (this *FunctionInfo) GetHandle() Handle{
	return this.h
}

func (this *FunctionInfo) SetHandle(h Handle){
	this.h = h
}



func (this *FunctionInfo) GetName() (name string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(function_info_get_name_id, xcall_params)  // call function pointer function_info_get_name_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionfunction_info.get_name. Error: %v", err)
		return
	}

	
	
	nameAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if nameAsInterface != nil{
		
		// not handle
		name = string(nameAsInterface.(string))
		
		
	}

	

	return name, nil	
}




func (this *FunctionInfo) GetComment() (comment string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(function_info_get_comment_id, xcall_params)  // call function pointer function_info_get_comment_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionfunction_info.get_comment. Error: %v", err)
		return
	}

	
	
	commentAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if commentAsInterface != nil{
		
		// not handle
		comment = string(commentAsInterface.(string))
		
		
	}

	

	return comment, nil	
}




func (this *FunctionInfo) GetParameters() (parameters []ParameterInfo, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(function_info_get_parameters_id, xcall_params)  // call function pointer function_info_get_parameters_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionfunction_info.get_parameters. Error: %v", err)
		return
	}

	
	
	parametersAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if parametersAsInterface != nil{
		 
		// handle
		
		 
		if len(parametersAsInterface.([]interface{})) > 0{
			parameters = make([]ParameterInfo, len(parametersAsInterface.([]interface{})))
			if _, ok := parametersAsInterface.([]interface{})[0].(Handle); ok{
				for i, h := range parametersAsInterface.([]interface{}){
					parameters[i] = ParameterInfo{ h: h.(Handle) }
				}
			} else {
				for i, obj := range parametersAsInterface.([]interface{}){
					parameters[i] = obj.(ParameterInfo)
				}
			}
		}
		
		

		
	}

	

	return parameters, nil	
}




func (this *FunctionInfo) GetReturnValues() (return_values []string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(function_info_get_return_values_id, xcall_params)  // call function pointer function_info_get_return_values_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionfunction_info.get_return_values. Error: %v", err)
		return
	}

	
	
	return_valuesAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if return_valuesAsInterface != nil{
		
		// not handle
		return_values = []string(return_valuesAsInterface.([]string))
		
		
	}

	

	return return_values, nil	
}





func (this *FunctionInfo) ReleasefunctionInfo( this_instance interface{}) ( err error){
	
	xcall_params, parametersCDTS, _ := XLLRAllocCDTSBuffer(1, 0)

	
	// parameters
	FromGoToCDT(this.h, parametersCDTS, 0) // object
	

		err = XLLRXCallParamsNoRet(function_info_Releasefunction_info_id, xcall_params)  // call function pointer function_info_Releasefunction_info_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionfunction_info.Releasefunction_info. Error: %v", err)
		return
	}

	
	

	return  nil
}


type ClassInfo struct{
	h Handle
}



func (this *ClassInfo) GetHandle() Handle{
	return this.h
}

func (this *ClassInfo) SetHandle(h Handle){
	this.h = h
}



func (this *ClassInfo) GetName() (name string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(class_info_get_name_id, xcall_params)  // call function pointer class_info_get_name_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionclass_info.get_name. Error: %v", err)
		return
	}

	
	
	nameAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if nameAsInterface != nil{
		
		// not handle
		name = string(nameAsInterface.(string))
		
		
	}

	

	return name, nil	
}




func (this *ClassInfo) GetComment() (comment string, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(class_info_get_comment_id, xcall_params)  // call function pointer class_info_get_comment_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionclass_info.get_comment. Error: %v", err)
		return
	}

	
	
	commentAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if commentAsInterface != nil{
		
		// not handle
		comment = string(commentAsInterface.(string))
		
		
	}

	

	return comment, nil	
}




func (this *ClassInfo) GetFields() (fields []VariableInfo, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(class_info_get_fields_id, xcall_params)  // call function pointer class_info_get_fields_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionclass_info.get_fields. Error: %v", err)
		return
	}

	
	
	fieldsAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if fieldsAsInterface != nil{
		 
		// handle
		
		 
		if len(fieldsAsInterface.([]interface{})) > 0{
			fields = make([]VariableInfo, len(fieldsAsInterface.([]interface{})))
			if _, ok := fieldsAsInterface.([]interface{})[0].(Handle); ok{
				for i, h := range fieldsAsInterface.([]interface{}){
					fields[i] = VariableInfo{ h: h.(Handle) }
				}
			} else {
				for i, obj := range fieldsAsInterface.([]interface{}){
					fields[i] = obj.(VariableInfo)
				}
			}
		}
		
		

		
	}

	

	return fields, nil	
}




func (this *ClassInfo) GetMethods() (methods []FunctionInfo, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(class_info_get_methods_id, xcall_params)  // call function pointer class_info_get_methods_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionclass_info.get_methods. Error: %v", err)
		return
	}

	
	
	methodsAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if methodsAsInterface != nil{
		 
		// handle
		
		 
		if len(methodsAsInterface.([]interface{})) > 0{
			methods = make([]FunctionInfo, len(methodsAsInterface.([]interface{})))
			if _, ok := methodsAsInterface.([]interface{})[0].(Handle); ok{
				for i, h := range methodsAsInterface.([]interface{}){
					methods[i] = FunctionInfo{ h: h.(Handle) }
				}
			} else {
				for i, obj := range methodsAsInterface.([]interface{}){
					methods[i] = obj.(FunctionInfo)
				}
			}
		}
		
		

		
	}

	

	return methods, nil	
}





func (this *ClassInfo) ReleaseclassInfo( this_instance interface{}) ( err error){
	
	xcall_params, parametersCDTS, _ := XLLRAllocCDTSBuffer(1, 0)

	
	// parameters
	FromGoToCDT(this.h, parametersCDTS, 0) // object
	

		err = XLLRXCallParamsNoRet(class_info_Releaseclass_info_id, xcall_params)  // call function pointer class_info_Releaseclass_info_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionclass_info.Releaseclass_info. Error: %v", err)
		return
	}

	
	

	return  nil
}


type PyInfo struct{
	h Handle
}



func (this *PyInfo) GetHandle() Handle{
	return this.h
}

func (this *PyInfo) SetHandle(h Handle){
	this.h = h
}



func (this *PyInfo) GetGlobals() (globals []VariableInfo, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(py_info_get_globals_id, xcall_params)  // call function pointer py_info_get_globals_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionpy_info.get_globals. Error: %v", err)
		return
	}

	
	
	globalsAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if globalsAsInterface != nil{
		 
		// handle
		
		 
		if len(globalsAsInterface.([]interface{})) > 0{
			globals = make([]VariableInfo, len(globalsAsInterface.([]interface{})))
			if _, ok := globalsAsInterface.([]interface{})[0].(Handle); ok{
				for i, h := range globalsAsInterface.([]interface{}){
					globals[i] = VariableInfo{ h: h.(Handle) }
				}
			} else {
				for i, obj := range globalsAsInterface.([]interface{}){
					globals[i] = obj.(VariableInfo)
				}
			}
		}
		
		

		
	}

	

	return globals, nil	
}




func (this *PyInfo) GetFunctions() (functions []FunctionInfo, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(py_info_get_functions_id, xcall_params)  // call function pointer py_info_get_functions_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionpy_info.get_functions. Error: %v", err)
		return
	}

	
	
	functionsAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if functionsAsInterface != nil{
		 
		// handle
		
		 
		if len(functionsAsInterface.([]interface{})) > 0{
			functions = make([]FunctionInfo, len(functionsAsInterface.([]interface{})))
			if _, ok := functionsAsInterface.([]interface{})[0].(Handle); ok{
				for i, h := range functionsAsInterface.([]interface{}){
					functions[i] = FunctionInfo{ h: h.(Handle) }
				}
			} else {
				for i, obj := range functionsAsInterface.([]interface{}){
					functions[i] = obj.(FunctionInfo)
				}
			}
		}
		
		

		
	}

	

	return functions, nil	
}




func (this *PyInfo) GetClasses() (classes []ClassInfo, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// get parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0)
	
	 


		err = XLLRXCallParamsRet(py_info_get_classes_id, xcall_params)  // call function pointer py_info_get_classes_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionpy_info.get_classes. Error: %v", err)
		return
	}

	
	
	classesAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if classesAsInterface != nil{
		 
		// handle
		
		 
		if len(classesAsInterface.([]interface{})) > 0{
			classes = make([]ClassInfo, len(classesAsInterface.([]interface{})))
			if _, ok := classesAsInterface.([]interface{})[0].(Handle); ok{
				for i, h := range classesAsInterface.([]interface{}){
					classes[i] = ClassInfo{ h: h.(Handle) }
				}
			} else {
				for i, obj := range classesAsInterface.([]interface{}){
					classes[i] = obj.(ClassInfo)
				}
			}
		}
		
		

		
	}

	

	return classes, nil	
}





func (this *PyInfo) ReleasepyInfo( this_instance interface{}) ( err error){
	
	xcall_params, parametersCDTS, _ := XLLRAllocCDTSBuffer(1, 0)

	
	// parameters
	FromGoToCDT(this.h, parametersCDTS, 0) // object
	

		err = XLLRXCallParamsNoRet(py_info_Releasepy_info_id, xcall_params)  // call function pointer py_info_Releasepy_info_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionpy_info.Releasepy_info. Error: %v", err)
		return
	}

	
	

	return  nil
}


type PyExtractor struct{
	h Handle
}


func NewPyExtractor( filename string) (instance *PyExtractor, err error){
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// parameters
	
	FromGoToCDT(filename, parametersCDTS, 0)
	

		err = XLLRXCallParamsRet(py_extractor_py_extractor_id, xcall_params)  // call function pointer py_extractor_py_extractor_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionpy_extractor.py_extractor. Error: %v", err)
		return
	}

	
	inst := &PyExtractor{}

	
	new_instanceAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if new_instanceAsInterface != nil{
		inst.h = new_instanceAsInterface.(Handle)
	} else {
		return nil, fmt.Errorf("Object creation returned nil")
	}
		
	

	return inst, nil	
}


func (this *PyExtractor) GetHandle() Handle{
	return this.h
}

func (this *PyExtractor) SetHandle(h Handle){
	this.h = h
}



func (this *PyExtractor) Extract() (info PyInfo, err error){
	
	

	xcall_params, parametersCDTS, return_valuesCDTS := XLLRAllocCDTSBuffer(1, 1)

	
	// parameters
	
	FromGoToCDT(this.h, parametersCDTS, 0) // object
	
	

		err = XLLRXCallParamsRet(py_extractor_extract_id, xcall_params)  // call function pointer py_extractor_extract_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionpy_extractor.extract. Error: %v", err)
		return
	}

	
	
	infoAsInterface := FromCDTToGo(return_valuesCDTS, 0)
	if infoAsInterface != nil{
		 		
		
		
		
		if obj, ok := infoAsInterface.(Handle); ok{ // None Go object			
			info = PyInfo{ h: obj }
		} else {
			info = PyInfo(infoAsInterface.(PyInfo))
		}
		

		
	}
	
	

	return info, nil
}


func (this *PyExtractor) ReleasepyExtractor( this_instance interface{}) ( err error){
	
	xcall_params, parametersCDTS, _ := XLLRAllocCDTSBuffer(1, 0)

	
	// parameters
	FromGoToCDT(this.h, parametersCDTS, 0) // object
	

		err = XLLRXCallParamsNoRet(py_extractor_Releasepy_extractor_id, xcall_params)  // call function pointer py_extractor_Releasepy_extractor_id via XLLR
	
	// check errors
	if err != nil{
		err = fmt.Errorf("Failed calling functionpy_extractor.Releasepy_extractor. Error: %v", err)
		return
	}

	
	

	return  nil
}




